export const VISIBLE_MINI_CART = "VISIBLE_MINI_CART";
export const VISIBLE_SEARCH_FORM = "VISIBLE_SEARCH_FORM";
export const VISIBLE_MENU = "VISIBLE_MENU";
export const ALL_DATA = "ALL_DATA";
export const PRODUCTS_DATA = "PRODUCTS_DATA";

